import { pick, localePath, codeBlock, esc } from '../lib/html.mjs';
import { site } from '../site.config.mjs';

/** Curated website guide, based on README.zh-CN.md blob 0cede5b8.
 * Keep product behavior in sync with the application repository. Source notes in docs/SOURCES.md.
 * Body strings here are trusted author-written HTML, not runtime/user input.
 */
export function getDocs(locale) {
  const t=(en,zh)=>pick(locale,en,zh),p=x=>localePath(locale,x);
  const para=(en,zh)=>`<p>${t(en,zh)}</p>`;
  return {
    'getting-started': {
      title:t('Open an existing Project on your Mac.','在 Mac 上打开现有 Project。'),
      label:t('Getting started','快速开始'),
      description:t('Install GitStride, connect GitHub, and open your existing Project.','安装 GitStride，连接 GitHub，打开你已有的 Project。'),
      icon:'monitor',
      sections:[
        {id:'requirements',title:t('Before you start','开始之前'),body:para('You need macOS 14 (Sonoma) or later and a GitHub.com account. Desktop browsing supports personal and organization Projects. GitHub Enterprise Server is not supported.','需要 macOS 14（Sonoma）或更新版本，以及 GitHub.com 账号。桌面端支持个人和组织 Projects，暂不支持 GitHub Enterprise Server。')+para(`Download the ZIP from the <a href="${p('download')}">download page</a>, unzip it, and move GitStride.app into Applications.`,`从<a href="${p('download')}">下载页</a>下载 ZIP，解压后将 GitStride.app 移入“应用程序”文件夹。`)},
        {id:'sign-in',title:t('Connect your GitHub account','连接 GitHub 账号'),body:`<ol><li>${t('Open GitStride. In the welcome window, choose <strong>Open GitHub Settings</strong>, then <strong>Log In to GitHub…</strong>.','打开 GitStride，在欢迎窗口选择<strong>打开 GitHub 设置</strong>，然后点击<strong>登录 GitHub…</strong>。')}</li><li>${t('Choose <strong>Copy Code and Open GitHub</strong>. Paste the code into GitHub’s device activation page and approve access.','选择<strong>复制代码并打开 GitHub</strong>，在 GitHub 的设备激活页面粘贴验证码并确认授权。')}</li><li>${t('Select your personal account or organization, then open a Project you already use.','选择个人账号或组织，再打开你已有的 Project。')}</li></ol>`+para('You can reopen connection settings under <strong>Settings → GitHub → Account</strong>. The welcome window can be reopened from <strong>Help → Welcome to GitStride…</strong>.','你可以随时通过<strong>设置 → GitHub → 账户</strong>管理连接，也可以从<strong>帮助 → 欢迎使用 GitStride…</strong>重新打开欢迎窗口。')},
        {id:'permissions',title:t('Know what you authorize','了解授权范围'),body:para('Desktop OAuth requests <code>repo project read:org offline_access</code>. The <code>repo</code> scope includes reading and writing repository code, including private repositories. It is broader than board-only access. Access and refresh tokens are stored in macOS Keychain.','桌面 OAuth 请求 <code>repo project read:org offline_access</code>。其中 <code>repo</code> 包括仓库代码读写及私有仓库访问，范围大于仅查看看板。访问令牌和刷新令牌保存在 macOS 钥匙串中。')+para(`Your GitHub permissions determine what you can view and edit. Organization policies or SSO may require additional authorization. Read <a href="${p('privacy')}">privacy and permissions</a> for local cache details.`,`可查看和编辑的内容由 GitHub 权限决定。组织策略和 SSO 可能要求额外授权。本地缓存说明见<a href="${p('privacy')}">隐私与权限</a>。`)},
        {id:'github-cli',title:t('Already using GitHub CLI?','已经使用 GitHub CLI？'),body:para('The GitHub Release build can reuse a CLI login. Install GitHub CLI, then run:','GitHub Release 版可以复用 CLI 登录。先安装 GitHub CLI，再运行：')+codeBlock('gh auth login --hostname github.com\ngh auth refresh --hostname github.com --scopes project,read:org',locale)+para('Disconnect the current app connection, then choose <strong>Settings → GitHub → Connection method → GitHub CLI</strong>. GitStride uses the account selected at connection time until you reconnect. Disconnecting GitStride does not log your terminal out of GitHub.','断开当前 App 连接后，选择<strong>设置 → GitHub → 连接方式 → GitHub CLI</strong>。GitStride 会继续使用连接时选定的账号，直到重新连接。断开 GitStride 不会退出终端中的 GitHub 登录。')},
        {id:'next',title:t('Continue with your existing workflow','继续使用现有工作流'),body:para(`Use the <a href="${p('docs/workspace')}">workspace guide</a> to explore views and editing. <a href="${p('docs/automation')}">PR automation</a> is optional and has a separate authorization flow; it is not required to browse or edit Projects.`,`通过<a href="${p('docs/workspace')}">工作区指南</a>了解视图与编辑。<a href="${p('docs/automation')}">PR 自动化</a>是可选功能，有独立授权流程；浏览和编辑 Project 不需要开启它。`)},
      ],
    },
    workspace:{
      title:t('Find the issues that need attention.','找到需要处理的 Issue。'),label:t('Workspace & views','工作区与视图'),icon:'board',
      description:t('Menu bar, boards, tables, and issue details—without a second backlog.','菜单栏、看板、表格与 Issue 详情，不必维护第二份待办。'),
      sections:[
        {id:'menu-bar',title:t('A quick check from the menu bar','从菜单栏快速查看'),body:para('Click the GitStride menu bar icon, select a Project, and browse issues by status. Open the full project window for a larger workspace.','点击 GitStride 菜单栏图标，选择 Project，按状态浏览 Issue。需要完整工作区时，打开项目窗口。')},
        {id:'board-table',title:t('Board or Table','看板与表格'),body:para('Use Board to move issues between status columns. Switch to Table when you need aligned fields and sorting. Search and item filters carry between layouts. Filter conditions and display options have different jobs: hiding a board column does not hide those items from Table.','使用看板在状态列之间移动事项；需要对齐字段与排序时切换到表格。搜索与事项筛选会在两种布局间保留。筛选与显示选项相互独立：隐藏看板列并不会过滤表格中的对应事项。')+para('On macOS 14.4 and later, multiple Project fields can appear as independent resizable and sortable table columns. macOS 14.0–14.3 supports one selected Project field column.','macOS 14.4 及以上支持将多个 Project 字段显示为可独立调整宽度和排序的表格列；macOS 14.0–14.3 支持一个选定的 Project 字段列。')},
        {id:'quick-create',title:t('Find an issue, or start one','查找事项，或快速创建'),body:para('Search by title, issue number, or <code>@username</code>. In the Project or menu bar search box, enter <code>&gt; Issue title</code> and press Return to open a prefilled creation form. Confirm the repository and status, then choose <strong>Create Issue</strong>. Return alone does not create the issue.','搜索支持标题、Issue 编号或 <code>@用户名</code>。在项目或菜单栏搜索框输入 <code>&gt; Issue 标题</code> 并按回车，打开预填内容的创建表单。确认仓库和状态后，点击<strong>创建 Issue</strong>。只按回车并不会直接创建。')+`<div class="shortcut-list"><span><kbd>⌘ R</kbd>${t('Refresh','刷新')}</span><span><kbd>⌘ ← / →</kbd>${t('Previous / next status tab','前一个 / 后一个状态标签页')}</span><span><kbd>Esc</kbd>${t('Cancel quick-create input','取消快速创建输入')}</span></div>`},
        {id:'my-work',title:t('Keep track across Projects','跨项目查看我的工作'),body:para('Add Projects to My Work and filter across them. Open an item to edit its issue, assignees, labels, milestone, parent/sub-issues, and dependencies, subject to your GitHub permissions.','将项目添加到“我的工作”，跨项目筛选与查看事项。打开条目，可按 GitHub 权限编辑 Issue、负责人、标签、里程碑、父子 Issue 和依赖关系。')},
        {id:'saved-views',title:t('Keep your preferred view','保留顺手的视图'),body:para('Save local work views with filters and display preferences. Saved views and display settings stay on this Mac; they do not modify saved views on GitHub. Search text is temporary.','保存包含筛选与显示偏好的本地工作视图。这些视图与设置只保存在当前 Mac，不会修改 GitHub 上保存的视图。搜索文字是临时的。')},
        {id:'notifications',title:t('Stay aware while the app runs','在 App 运行时接收提醒'),body:para('When enabled, project reminders periodically check Projects in My Work while GitStride is running. They can notify you about status changes, assignment changes, and approaching or overdue dates. This is separate from the hosted PR automation that can run after you quit the app.','启用项目提醒后，GitStride 会在 App 运行期间定期检查“我的工作”中的项目，提醒状态变更、任务分配变动、临期或逾期事项。这与退出 App 后仍运行的托管 PR 自动化不是同一项功能。')},
      ],
    },
    automation:{
      title:t('Keep Project status in step with pull requests.','让 Project 状态跟随 PR 进展。'),label:t('Set up PR automation','设置 PR 自动化'),icon:'branch',
      description:t('Set up an optional, separate connection that updates issue status in matching personal Projects.','配置独立、可选的自动化连接，让关联 PR 更新 Issue 在匹配的个人 Project 中的状态。'),
      sections:[
        {id:'connect',title:t('Authorize the two connections','完成两项授权'),body:para('Open <strong>Settings → GitHub → Pull Request Automation → Set Up Automation</strong>. Install the GitHub App for the repositories you allow, then authorize the separate OAuth App with <code>project offline_access</code>. Desktop authentication and automation authentication are managed separately.','进入<strong>设置 → GitHub → PR 自动化 → 设置自动化</strong>。安装 GitHub App，允许它访问所选仓库；再授权独立的 OAuth App 使用 <code>project offline_access</code>。桌面登录与自动化授权分别管理。')},
        {id:'mapping',title:t('Choose the mapping template','选择映射模板'),body:para('Choose a personal Project and map its Status field, In Progress, and Done options. All repositories currently allowed for the GitHub App installation are included. The field and option names are applied to every compatible personal Project containing the closing Issue; the template is not the only Project that may change.','选择个人 Project，映射其状态字段与 In Progress、Done 选项。GitHub App 当前获准访问的所有仓库都会纳入处理。自动化按字段名与状态名匹配包含该 Issue 的所有兼容个人 Projects；并不只更新模板 Project。')+para('Choose <strong>Move to In review</strong> or <strong>Keep in In Progress</strong> for Ready PRs. The first policy adds an orange In review option when needed if the matching Project does not already have it.','为 Ready PR 选择<strong>移至 In review</strong>或<strong>保持在 In Progress</strong>。前一种策略会在匹配 Project 缺少该状态且首次需要时，添加橙色 In review 选项。')},
        {id:'link-issue',title:t('Link a pull request to an issue','让 PR 关联并关闭 Issue'),body:para('Add the Issue to a personal Project. For a PR in the same repository, put a closing keyword in the PR <strong>description</strong> and target the repository’s default branch. For example:','把 Issue 加入个人 Project。对于同仓库 PR，在 PR <strong>描述</strong>中填写关闭关键词，并将目标分支设为仓库的默认分支。例如：')+codeBlock('Closes #123',locale)+para('Replace 123 with the actual Issue number. Check the relationship in GitHub. Automation changes the Issue’s Project item status, not merely the Issue’s open/closed state.','将 123 换成实际 Issue 编号，并在 GitHub 确认关联。自动化更新的是 Issue 的 Project 条目状态，不只是 Issue 的打开或关闭状态。')},
        {id:'rules',title:t('Understand the state rules','理解状态规则'),body:`<ol><li>${t('Any open closing Draft PR keeps the Issue In Progress.','存在打开的关闭关联 Draft PR：保持 In Progress。')}</li><li>${t('No open Draft, but an open closing Ready PR: apply your chosen review policy.','没有打开的 Draft，但存在打开的关闭关联 Ready PR：执行选定的评审策略。')}</li><li>${t('At least one closing PR, with all closing PRs merged: move to Done.','至少有一个关闭关联 PR，且全部已合并：移至 Done。')}</li></ol>`+para('Processing waits at least three seconds before reading current state; queue and network time add to the delay. Disabling overlapping built-in Project status workflows is recommended to avoid competing updates.','处理前会等待至少三秒再读取当前状态，此外还有队列和网络耗时。建议关闭与这些规则重叠的 GitHub Project 内置状态工作流，避免同时修改状态。')},
        {id:'manage',title:t('Pause or disconnect','暂停或断开'),body:para('Pause, resume, reauthorize, or delete the automation connection in Settings. Deletion stops future processing but does not undo prior Project status changes. To revoke GitHub access as well, remove the corresponding OAuth authorization and uninstall the GitHub App.','在设置中暂停、恢复、重新授权或删除自动化连接。删除停止后续处理，但不撤销已有 Project 状态变化。要同时撤销 GitHub 访问，还需撤销对应 OAuth 授权并卸载 GitHub App。')+para('<a href="https://github.com/settings/applications">Authorized OAuth Apps</a> · <a href="https://github.com/settings/installations">Installed GitHub Apps</a>','<a href="https://github.com/settings/applications">Authorized OAuth Apps</a> · <a href="https://github.com/settings/installations">Installed GitHub Apps</a>')},
      ],
    },
    'self-hosting':{
      title:t('Run automation on your terms.','让自动化运行在自己的服务上。'),label:t('Self-hosting','自托管'),icon:'terminal',
      description:t('Connect the desktop app to your own Cloudflare Worker.','把桌面 App 连接到自己的 Cloudflare Worker。'),
      sections:[
        {id:'deploy',title:t('Deploy the Worker first','先部署 Worker'),body:para(`Follow the <a href="${site.workerGuide}">repository’s deployment guide</a> for GitHub App registration, OAuth configuration, secrets, queues, and database setup. Keep those operational instructions in the application repository as the source of truth.`,`GitHub App 注册、OAuth 配置、密钥、队列与数据库设置请遵循<a href="${site.workerGuide}">应用仓库的部署指南</a>，以仓库中的运维说明为准。`)+para('The product website on Vercel is separate from this service. Deploying the website does not enable automation or deploy a Worker. Never put GitHub tokens, Client Secrets, or Worker credentials into this website’s configuration.','Vercel 上的产品官网与自动化服务相互独立。部署官网不会启用自动化，也不会部署 Worker。不要把 GitHub 令牌、Client Secret 或 Worker 凭据写入官网配置。')},
        {id:'connect-service',title:t('Set a custom service address','设置自定义服务地址'),body:`<ol><li>${t('Open <strong>Settings → GitHub → Pull Request Automation → Automation Service</strong>.','打开<strong>设置 → GitHub → PR 自动化 → 自动化服务</strong>。')}</li><li>${t('Choose <strong>Custom address</strong> and enter the Worker’s HTTPS service address.','选择<strong>自定义地址</strong>，填写 Worker 的 HTTPS 服务地址。')}</li><li>${t('Save and restart GitStride, then connect automation on the selected service. No app rebuild is required.','保存并重启 GitStride，然后在选定的服务上连接自动化。无需重新编译 App。')}</li></ol>`},
        {id:'switching',title:t('Switching is not server shutdown','切换地址不等于停止旧服务'),body:para('Switching to another service, the default service, or Disabled only changes this Mac’s connection. Pause or delete the old connection before switching if you need the old server to stop processing. Management credentials are isolated by service address.','切换为其他地址、默认服务或禁用，只会改变这台 Mac 的连接。需要停止旧服务器处理时，应先暂停或删除旧连接。管理凭据按服务地址隔离。')},
        {id:'source-build',title:t('Configure a source build','源码构建配置'),body:para('The <code>GITSTRIDE_AUTOMATION_BASE_URL</code> build setting supplies the default service address. An empty value means no default service is supplied; a custom service address can still be entered in the app.','<code>GITSTRIDE_AUTOMATION_BASE_URL</code> 构建设置指定默认服务地址。留空表示不提供默认服务，但用户仍可在 App 中设置自定义地址。')},
      ],
    },
  };
}
