import { esc, pick, localePath } from '../lib/html.mjs';
import { getDocs } from '../content/docs.mjs';
import { icon } from './icons.mjs';
import { site } from '../site.config.mjs';

export function docsPage(locale, slug = '') {
  const t=(en,zh)=>pick(locale,en,zh), p=x=>localePath(locale,x), docs=getDocs(locale);
  const sidebar=`<aside class="docs-sidebar"><a class="docs-home ${!slug?'active':''}" href="${p('docs')}">${icon('book')}${t('GitStride documentation','GitStride 文档')}</a><p class="sidebar-heading">${t('GET STARTED','开始使用')}</p><nav aria-label="${t('Documentation pages','文档页面')}">${Object.entries(docs).map(([key,doc])=>`<a href="${p('docs/'+key)}" ${slug===key?'aria-current="page"':''}>${icon(doc.icon)}${doc.label}</a>`).join('')}</nav><p class="sidebar-heading">${t('REFERENCE','参考')}</p><nav aria-label="${t('Reference pages','参考页面')}"><a href="${p('privacy')}">${icon('shield')}${t('Privacy & permissions','隐私与权限')}</a><a href="${p('support')}">${icon('issue')}${t('Troubleshooting','问题排查')}</a><a href="${locale==='en'?site.sourceGuide:site.sourceGuideZh}">${icon('github')}${t('Repository README','仓库 README')}${icon('upRight')}</a></nav></aside>`;
  if(!slug) return `<main id="main" class="container docs-layout">${sidebar}<article class="docs-index"><p class="eyebrow">${t('A LITTLE GUIDANCE. THEN, GET GOING.','从这里开始，把工作推进。')}</p><h1>${t('Make yourself<br>at home.','欢迎来到<br>你的新工作区。')}</h1><p class="page-description">${t('Start with your GitHub account. Find a view that fits. Connect automation when you are ready.','从连接 GitHub 账号开始，找到适合自己的视图，再按需开启自动化。')}</p><div class="docs-card-grid">${Object.entries(docs).map(([key,doc],i)=>`<a class="docs-card" href="${p('docs/'+key)}"><div>${icon(doc.icon)}<span class="mono">0${i+1}</span></div><h2>${doc.label}</h2><p>${doc.description}</p><span class="card-arrow">${icon('arrow')}</span></a>`).join('')}</div><div class="docs-help">${icon('issue')}<div><h2>${t('Something not working?','遇到问题？')}</h2><p>${t('Find connection checks and a clear path to reporting an issue.','查看连接排查方法，或提交可复现的问题。')}</p></div><a class="text-link" href="${p('support')}">${t('Get support','获取支持')}${icon('arrow')}</a></div></article></main>`;
  const doc=docs[slug]; if(!doc) throw new Error('Unknown document '+slug);
  const keys=Object.keys(docs),index=keys.indexOf(slug),next=keys[index+1];
  return `<main id="main" class="container docs-layout">${sidebar}<article class="doc-article"><div class="doc-breadcrumb"><a href="${p('docs')}">${t('Docs','文档')}</a>${icon('chevron')}<span>${doc.label}</span></div><h1>${doc.title}</h1><p class="page-description">${doc.description}</p><nav class="doc-toc" aria-label="${t('On this page','本页目录')}"><strong>${t('On this page','本页内容')}</strong>${doc.sections.map(s=>`<a href="#${s.id}">${s.title}</a>`).join('')}</nav><div class="prose">${doc.sections.map(s=>`<section id="${s.id}"><h2>${s.title}<a class="heading-anchor" href="#${s.id}" aria-label="${t('Link to section','链接到此节')}">#</a></h2>${s.body}</section>`).join('')}</div><div class="doc-end"><a href="${locale==='en'?site.sourceGuide:site.sourceGuideZh}">${t('Product behavior reference: repository README','产品行为依据：仓库 README')}${icon('upRight')}</a>${next?`<a class="next-doc" href="${p('docs/'+next)}"><small>${t('NEXT','下一篇')}</small>${docs[next].label}${icon('arrow')}</a>`:`<a class="text-link" href="${p('docs')}">${t('Back to documentation','返回文档目录')}${icon('arrow')}</a>`}</div></article></main>`;
}
