import { pick, localePath } from '../lib/html.mjs';
import { ui } from '../content/ui.mjs';
import { icon } from './icons.mjs';
import { workspace, menubar, issuePreview, automationDemo } from './previews.mjs';
import { cta } from './shell.mjs';
import { site } from '../site.config.mjs';

export function home(locale) {
  const t=(en,zh)=>pick(locale,en,zh),u=ui[locale],p=x=>localePath(locale,x);
  return `<main id="main">
  <section class="hero container"><a class="hero-eyebrow" href="${p('automation')}"><span class="eyebrow-dot"></span>${t('GITHUB-NATIVE. MAC-NATIVE.','你的 GitHub 工作流，原生 Mac 体验。')}<span class="eyebrow-separator"></span>${t('Meet GitStride','认识 GitStride')}${icon('arrow')}</a><h1>GitHub Projects.<br><span>${t('At home on your Mac.','在 Mac 上更顺手。')}</span></h1><p class="hero-description">${t('Check project progress from the menu bar, then manage issues in boards and tables. Bring your existing GitHub Projects into a native Mac app—and keep the workflow you already know.','从菜单栏快速查看项目进展，再到看板和表格中处理 Issue。<br>把现有的 GitHub Projects 带进原生 Mac 应用，继续沿用你熟悉的工作流。')}</p><div class="hero-actions"><a class="button button-primary" href="${p('download')}">${icon('apple')}${u.downloadMac}${icon('arrow')}</a><a class="button button-quiet" href="#workspace">${t('Explore the workspace','看看工作区')}${icon('down')}</a></div><p class="hero-requirements">${u.requirements}</p></section>
  <section class="showcase-container" id="workspace" aria-label="${t('Workspace preview','工作区预览')}">${workspace(locale)}</section>
  <div class="container product-signals"><span>${icon('monitor')}${t('Native macOS app','原生 macOS 应用')}</span><span>${icon('github')}${t('Use your existing GitHub Projects','直接使用现有 GitHub Projects')}</span><span>${icon('branch')}${t('Optional PR automation','按需开启 PR 自动化')}</span><a href="${site.github}">${icon('terminal')}${t('MIT-licensed','MIT 开源')}${icon('upRight')}</a></div>
  <section class="container editorial-intro"><p class="eyebrow">${t('SAME PROJECTS. A NATIVE MAC WORKSPACE.','同一份项目，一个原生 Mac 工作区。')}</p><h2>${t('Your projects stay on GitHub.<br><span>Manage them with less friction.</span>','项目仍在 GitHub。<br><span>管理起来更顺手。</span>')}</h2><p>${t('GitStride lets you view and manage your existing issues and Projects in a focused Mac workspace. No second backlog to maintain and no entirely new workflow to adopt.','GitStride 让你在专注的 Mac 工作区里查看和管理现有的 Issue 与 Project。无需维护第二份待办，也不用适应一套全新的流程。')}</p></section>
  <section class="container feature-split" id="menubar"><div class="feature-copy"><p class="section-index">01 <span>/</span> ${t('CLOSER AT HAND','随手可达')}</p><h2>${t('A glance.<br>Not a detour.','看一眼项目，<br>不打断思路。')}</h2><p>${t('Check a project from the menu bar, find an issue, then get back to what you were doing. Open the full workspace when it is time to dig in.','从菜单栏查看项目、找到事项，然后继续手头的工作。需要深入处理时，再打开完整工作区。')}</p><a class="text-link" href="${p('docs/workspace')}#menu-bar">${t('Meet your menu bar companion','了解菜单栏工作方式')}${icon('arrow')}</a><div class="feature-footnote">${icon('search')} ${t('Search by title, issue number, or @assignee.','按标题、Issue 编号或 @负责人搜索。')}</div></div>${menubar(locale)}</section>
  <section class="container feature-split feature-reverse"><div class="feature-copy"><p class="section-index">02 <span>/</span> ${t('LESS CONTEXT SWITCHING','减少来回切换')}</p><h2>${t('See the whole picture.<br>Make the next move.','看清全局，<br>推进下一步。')}</h2><p>${t('Switch freely between board and table views. Use search and filters to find the issues that need your attention. Edit issue details, assignees, and status directly to keep the project moving.','在看板和表格间自由切换，通过搜索和筛选快速找到需要处理的 Issue。直接编辑内容、调整负责人和状态，让项目继续向前。')}</p><a class="text-link" href="${p('docs/workspace')}">${t('Explore the workspace guide','了解工作区')}${icon('arrow')}</a><div class="feature-footnote">${icon('monitor')}${t('Search and filters carry over when you switch between board and table views.','切换看板与表格时，搜索和筛选条件保持不变。')}</div></div>${issuePreview(locale)}</section>
  <section class="automation-section"><div class="container"><div class="section-topline"><div><p class="section-index">03 <span>/</span> ${t('PROGRESS, CONNECTED','让进度关联起来')}</p><h2>${t('When the code moves,<br><span>the project follows.</span>','让项目进度，<br><span>跟上代码进度。</span>')}</h2></div><div><p>${t('Let linked pull requests update an issue’s status in matching personal Projects. The optional service keeps running, even when you close GitStride.','让关联 PR 的进展，更新 Issue 在匹配的个人 Project 中的状态。可选的自动化服务，在退出 GitStride 后仍会运行。')}</p><a class="text-link" href="${p('automation')}">${u.learnMore}${icon('arrow')}</a></div></div>${automationDemo(locale,true)}<p class="section-caption">${t('Personal Projects · Separate authorization · Your choice of review policy','个人 Projects · 独立授权 · 自选评审策略')}</p></div></section>
  <section class="container confidence-section"><div class="confidence-intro"><p class="eyebrow">${t('FAMILIAR FOUNDATIONS','建立在熟悉的基础上')}</p><h2>${t('A lighter workspace.<br>Clear boundaries.','更轻的工作区，<br>清楚的数据边界。')}</h2></div><div class="confidence-grid"><article>${icon('github')}<h3>${t('GitHub stays the source','仍以 GitHub 为准')}</h3><p>${t('Desktop browsing and editing talk directly to GitHub. Personal and organization Projects are supported.','桌面端浏览与编辑直接请求 GitHub，支持个人和组织 Projects。')}</p></article><article>${icon('shield')}<h3>${t('Understand what you authorize','了解你授予的权限')}</h3><p>${t('Login credentials live in macOS Keychain. Desktop OAuth requests broad repository access; local project snapshots are not encrypted.','登录凭据保存在 macOS 钥匙串。桌面 OAuth 包含较宽的仓库权限；本地项目快照未经加密。')}</p></article><article>${icon('terminal')}<h3>${t('Inspect it. Make it yours.','可以查看，也可以自托管')}</h3><p>${t('Explore the MIT-licensed source. Use the optional hosted automation service, or connect your own Worker.','查看 MIT 许可的源代码。按需使用托管自动化服务，或连接自己的 Worker。')}</p></article></div><a class="text-link" href="${p('privacy')}">${u.privacy}${icon('arrow')}</a></section>
  ${cta(locale)}</main>`;
}
export function automationPage(locale) {
  const t=(en,zh)=>pick(locale,en,zh),p=x=>localePath(locale,x);
  return `<main id="main"><section class="container page-hero automation-hero"><p class="eyebrow">${icon('branch')} ${t('PULL REQUEST AUTOMATION','PULL REQUEST 自动化')}</p><h1>${t('As pull requests move,<br><span>project status follows.</span>','PR 状态变化，<br><span>项目进度自动跟进。</span>')}</h1><p>${t('From Draft to Ready for review to Merged, linked pull requests update issue status in matching personal Projects—even after you quit GitStride.','从 Draft、Ready for review 到 Merged，关联 PR 的状态变化会自动更新 Issue 在匹配的个人 Project 中的状态。即使退出 GitStride，自动化仍会继续运行。')}</p><div class="hero-actions"><a class="button button-primary" href="${p('docs/automation')}">${t('Set up automation','设置自动化')}${icon('arrow')}</a><a class="button button-quiet" href="#how-it-works">${t('See how it works','看看如何流转')}${icon('down')}</a></div><p class="fine-print">${t('Optional · Personal Projects · Separate from desktop login','可选功能 · 个人 Projects · 与桌面登录分别授权')}</p></section><section class="container" id="how-it-works">${automationDemo(locale)}</section>
  <section class="container rules-section"><div class="section-topline"><h2>${t('The full PR picture<br>determines the next status.','根据整组 PR 的状态，<br>决定 Issue 的下一步。')}</h2><p>${t('A single issue can have more than one closing PR. GitStride checks the current set before choosing its next Project status.','一个 Issue 可以关联多个关闭 PR。GitStride 会检查这一组 PR 的当前状态，再决定下一个 Project 状态。')}</p></div><div class="rule-grid"><article><span class="rule-number">01</span><i class="status-dot progress"></i><h3>${t('Drafts still open','仍有 Draft')}</h3><p>${t('Any open Draft PR keeps the issue In Progress.','只要还有打开的 Draft PR，Issue 就保持在 In Progress。')}</p></article><article><span class="rule-number">02</span><i class="status-dot review"></i><h3>${t('Ready for review','准备评审')}</h3><p>${t('With no open Draft and at least one open Ready PR, use your chosen review policy.','没有打开的 Draft，但仍有打开的 Ready PR 时，按你选择的评审策略处理。')}</p></article><article><span class="rule-number">03</span><i class="status-dot done"></i><h3>${t('All closing PRs merged','全部合并')}</h3><p>${t('There must be at least one closing PR, and all closing PRs must be merged, before the issue moves to Done.','至少有一个关闭关联 PR，并且所有关闭关联 PR 都已合并，Issue 才进入 Done。')}</p></article></div></section>
  <section class="container setup-section"><div><p class="eyebrow">${t('CONNECT ONCE. STAY IN CONTROL.','连接一次，始终可控。')}</p><h2>${t('Your projects.<br>Your mapping.','你的项目，<br>你的状态映射。')}</h2><p>${t('Choose a personal Project as the mapping template. Compatible personal Projects containing the issue use those same field and status names—not just the template Project.','选择一个个人 Project 作为映射模板。包含关联 Issue、且字段名和状态名匹配的个人 Projects 都会被处理，并不只更新模板 Project。')}</p><a class="text-link" href="${p('docs/automation')}">${t('Read the complete setup guide','阅读完整设置指南')}${icon('arrow')}</a></div><div class="setup-steps"><article><span>1</span><div><h3>${t('Choose the repositories','选择仓库')}</h3><p>${t('Install the GitHub App. Every repository currently allowed for that installation is included.','安装 GitHub App；该安装当前获准访问的所有仓库都会被纳入处理。')}</p></div></article><article><span>2</span><div><h3>${t('Authorize Project updates','授权 Project 更新')}</h3><p>${t('Authorize the separate OAuth App with project and offline_access. Desktop login alone does not enable automation.','授权独立的 OAuth App 使用 project 与 offline_access。仅完成桌面登录不会启用自动化。')}</p></div></article><article><span>3</span><div><h3>${t('Set the mapping and policy','指定映射和策略')}</h3><p>${t('Map In Progress and Done, then choose whether Ready PRs move to In review or stay In Progress.','映射 In Progress 和 Done，再选择 Ready PR 移至 In review 或保持 In Progress。')}</p></div></article></div></section>
  <section class="container control-strip"><div>${icon('settings')}<h3>${t('Pause when you need to','随时暂停')}</h3><p>${t('Pause, resume, reauthorize, or delete the connection in Settings. Deleting it does not undo earlier status changes.','在设置中暂停、恢复、重新授权或删除连接。删除不会撤销先前的状态修改。')}</p></div><div>${icon('terminal')}<h3>${t('Host your own automation service','自行托管自动化服务')}</h3><p>${t('Deploy to your own Cloudflare account, then select a custom HTTPS service address in the app.','部署到自己的 Cloudflare 账号，再在 App 中设置自定义 HTTPS 服务地址。')}</p><a class="text-link" href="${p('docs/self-hosting')}">${t('Self-hosting guide','自托管指南')}${icon('arrow')}</a></div></section>${cta(locale)}</main>`;
}
